#!/bin/bash

export VENV_NAME="`basename $VIRTUAL_ENV`"

# This hook is run after every virtualenv is activated.
script="$VENV_HOOKS_HOME/postactivate-"$(basename $VIRTUAL_ENV)
if [ -r $script ]; then
    source $script
fi
