#!/bin/bash
# basic alias colelction

alias l="ls"
alias ll="la -l"
alias la="ls -la"

alias ..="cd .."

alias sshci="ssh-copy-id -i ~/.ssh/id_rsa.pub"

alias hosts="sudo vim /etc/hosts"

alias fuck='sudo $(history -p \!\!)'
alias bash-l='. ~/.bashrc'
