#!/bin/bash

function echoc {
	FG=$1
	BG=$2
	MSG=$3

	# PS1 needs extra escape charecters
	IS_PS=$4
	if [ ! -z $IS_PS ]
	then
		ESC="\["
		CSE="\]"
	else
		ESC=""
		CSE=""
	fi

	echo -en "$ESC$(tput setaf $FG)$(tput setab $BG)$CSE"
        echo -en "$MSG"
        echo -en "$ESC$(tput sgr0)$CSE"
}
