#!/bin/bash

function echoc {
	FG=$1
	BG=$2
	MSG=$3

	# PS1 needs extra escape charecters
	IS_PS=$4
	if [ ! -z $IS_PS ]
	then
		ESC="\["
		CSE="\]"
	else
		ESC=""
		CSE=""
	fi

	echo -e "$ESC$(tput setaf $FG)$CSE$ESC$(tput setab $BG)$CSE$MSG$ESC$(tput sgr0)$CSE"
}
