#!/bin/bash

GIT_SOURCE_FILE="/usr/local/etc/bash_completion.d/git-prompt.sh"

if [ -f "$GIT_SOURCE_FILE" ]
then
    source "$GIT_SOURCE_FILE"
else
    if ! hash __git_ps1 > /dev/null 2>&1
    then
        function __git_ps1 {
            return
        }
    fi
fi
GIT_PS1_SHOWDIRTYSTATE=true
