#!/bin/bash

# Grabbed from jimeh/git-aware-prompt
find_git_branch() {
  # Based on: http://stackoverflow.com/a/13003854/170413
  local branch
  if branch=$(git rev-parse --abbrev-ref HEAD 2> /dev/null); then
    if [[ "$branch" == "HEAD" ]]; then
      branch='detached*'
    fi
    local git_branch="$branch"
  else
    local git_branch=""
  fi
  echo "$git_branch"
}

find_git_dirty() {
  local status=$(git status --porcelain 2> /dev/null)
  if [[ "$status" != "" ]]; then
    local git_dirty='*'
  else
    local git_dirty=''
  fi
  echo "$git_dirty"
}

function git_prompt {
local branch="$(find_git_branch)"
    DIRTY_BRANCH=""
    PIPEC=""
    if [ ! -z "$branch" ]
    then
        DIRTY_BRANCH="`wrap_blue 1 $branch$(find_git_dirty)`"
        PIPEC="|"
    fi
    echo "$DIRTY_BRANCH$PIPEC"
}

GIT_SOURCE_FILE="/usr/local/etc/bash_completion.d/git-prompt.sh"

if [ -f "$GIT_SOURCE_FILE" ]
then
    source "$GIT_SOURCE_FILE"
else
    if ! hash __git_ps1 > /dev/null 2>&1
    then
        function __git_ps1 {
            return
        }
    fi
fi
GIT_PS1_SHOWDIRTYSTATE=true
