#!/bin/bash
alias camr='sudo killall VDCAssistant; sudo killall AppleCameraAssistant'

alias battery="[ \"`uname`\" == \"Darwin\" ] && ioreg -l | grep -i capacity \
| tr '\n' ' | ' | awk '{printf(\"%.2f%%\", \$10/\$5 * 100)}'"

function hey {
    echo "heyhey"
}
