#!/bin/bash

# Python Virtual Environment
export WORKON_HOME=~/.virtualenvs
VENVW=`which virtualenvwrapper.sh 2> /dev/null`
if [ ! "$VENVW" == "" ]
then
    export VIRTUALENVWRAPPER_PYTHON=`which python`
    export VIRTUALENVWRAPPER_VIRTUALENV=`which virtualenv`
    source $VENVW
fi

# These are the global hooks that trigger the per venv ones
export VIRTUALENVWRAPPER_HOOK_DIR="$HOME/.venv.d"
# The following are per venv hooks stored in private.d
export VENV_HOOKS_HOME="$HOME/.private.d/venv-hooks"
export VIRTUAL_ENV_DISABLE_PROMPT=1

function __venv_prompt {
    fmt="$1"
    venv="${VIRTUAL_ENV:+$(basename $VIRTUAL_ENV)}"
    if [ ! -z "$venv" ]
    then
        printf -- "$fmt" "$venv"
    fi
}

export PIP_DOWNLOAD_CACHE="~/.pip/repository"
