#!/bin/bash

# Python Virtual Environment
export WORKON_HOME=~/.virtualenvs
VENVW=`which virtualenvwrapper.sh 2> /dev/null`
if [ ! "$VENVW" == "" ]
then
    source $VENVW
    export VIRTUALENVWRAPPER_PYTHON=`which python`
    export VIRTUALENVWRAPPER_VIRTUALENV=`which virtualenv`
fi

# TODO: Deal with all venv hook stuff
export VENV_HOOKS_HOME="$HOME/.private.d/venv-hooks"
export VIRTUAL_ENV_DISABLE_PROMPT=1
ln -sf "$HOME/.venv.d/postactivate" "$WORKON_HOME/postactivate"
ln -sf "$HOME/.venv.d/postdeactivate" "$WORKON_HOME/postdeactivate"

function __venv_prompt {
    fmt="$1"
    venv="${VIRTUAL_ENV:+$(basename $VIRTUAL_ENV)}"
    if [ ! -z "$venv" ]
    then
        printf "$fmt" "$venv"
    fi
}

export PIP_DOWNLOAD_CACHE="~/.pip/repository"
