#!/bin/bash

function assh {
    MPORT="$((10000 + $RANDOM % 1000))"
    echo "Using autossh: $MPORT"
    autossh -M $MPORT $@
}

if [ ! -z "`which autossh 2> /dev/null`" ]
then
    alias ssh="assh"
fi

