#!/bin/bash

# When on my personal laptop, I do not need the hostname in the prompt
if [[ "`hostname`" =~ ^n9code.* ]]
then
    export PS_TEXT="`wrap_brown 1 '\w\$'` "
else
    export PS_TEXT="`wrap_white 1 '\u@\h'`:`wrap_brown 1 '\w\$'` "
fi

# export CLICOLOR=1
export PS1="\[\033[$CLR_GREEN\]\$(__venv_prompt \"%s|\")\[\033[$CLR_RESET\]\
\[\033[$CLR_BLUE\]\$(__git_ps1 \"%s|\")\[\033[$CLR_RESET\]\
${PS_TEXT}"

export EDITOR='vim'
