#!/bin/bash

# Define the variable depending on which host I am on, i.e. when
# on my laptop, the init style should be the active one,
# otherwise - inactive.
if [[ $HOSTNAME =~ ^n9code ]]
then
    export TMUX_INIT_STYLE="$HOME/.tmux/styles-active.conf"
else
    export TMUX_INIT_STYLE="$HOME/.tmux/styles-inactive.conf"
fi

# Ignoring M-F11 and M-F12
bind '"3;2~":""'
bind '"4;2~":""'

# export TERM=xterm-256color
# export DISPLAY=:0.0
