#!/bin/bash

# Define the variable depending on which host I am on, i.e. when
# on my laptop, the init style should be the active one,
# otherwise - inactive.
if [ $HELLO_ITS_ME == "1" ]
then
    export TMUX_INIT_STATE="active"
else
    export TMUX_INIT_STATE="inactive"
fi
